import { test, expect } from '@playwright/test';

test('Creacion de nueva cancha con rol club', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('kickfc@gmail.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('distrito1234');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.getByText('¡Hola Kick FC!')).toBeVisible();
  await page.getByText('K', { exact: true }).click();
  await expect(page.getByRole('link', { name: 'Reservas' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cargar Cancha' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cerrar Sesión' })).toBeVisible();
  await page.getByRole('link', { name: 'Reservas' }).click();
  await expect(page.getByRole('heading', { name: 'Reservas del Club' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Horarios de turnos' })).toBeVisible();
  await page.getByRole('button', { name: 'Horarios de turnos' }).click();
  await page.getByRole('button', { name: 'Ver turnos cargados' }).click();
  await expect(page.getByLabel('Ver turnos cargados').locator('div').filter({ hasText: 'CanchaTurnosCancha 1 F5Lunes' }).first()).toBeVisible();
  await page.getByRole('combobox').first().click();
  await page.getByRole('option', { name: 'Lunes' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Martes' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Miércoles' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Jueves' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Viernes' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Sábado' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Domingo' }).getByRole('checkbox').check();
  await page.getByRole('option', { name: 'Domingo' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Sábado' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Viernes' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Jueves' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Miércoles' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Martes' }).getByRole('checkbox').uncheck();
  await page.getByRole('option', { name: 'Lunes' }).getByRole('checkbox').uncheck();
  await page.locator('.MuiBackdrop-root').click();
  await page.getByRole('combobox').nth(1).click();
  await page.getByRole('option', { name: 'Cancha 1 F5' }).click();
  await page.getByRole('button', { name: 'Volver a reservas' }).click();
  await expect(page.getByRole('heading', { name: 'Reservas del Club' })).toBeVisible();
  await page.getByText('K', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});

test('Verificacion de canchas cargadas con rol club', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('kickfc@gmail.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('distrito1234');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.getByText('¡Hola Kick FC!')).toBeVisible();
  await page.getByText('K', { exact: true }).click();
  await expect(page.getByRole('link', { name: 'Reservas' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cargar Cancha' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cerrar Sesión' })).toBeVisible();
  await page.getByRole('link', { name: 'Cargar Cancha' }).click();
  await expect(page.getByRole('heading', { name: 'Crear nueva cancha' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tus canchas' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Datos de la cancha a crear' })).toBeVisible();
  await page.getByLabel('Crear Nombre').click();
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('C');
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('Cancha 8 ');
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('Cancha 8 F8');
  await page.getByLabel('Open').first().click();
  await page.getByRole('option', { name: 'Fútbol 8' }).click();
  await page.getByLabel('Open').nth(1).click();
  await page.getByRole('option', { name: 'CESPED_NATURAL' }).click();
  await page.getByLabel('Open').nth(2).click();
  await page.getByRole('option', { name: 'NO' }).click();
  await expect(page.getByRole('button', { name: 'Crear cancha' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear cancha' }).click();
  await expect(page.getByRole('heading', { name: 'Cancha Creada' })).toBeVisible();
  await expect(page.getByText('Cancha Creada¡La cancha se ha')).toBeVisible();
  await page.getByRole('button', { name: '¡OK!' }).click();
  await page.getByText('K', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});