import { test, expect } from '@playwright/test';

test('Sumarse evento con usuario logueado', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('jilmelarke@gufum.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('89898989');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await page.getByRole('combobox', { name: 'Elegir Actividad' }).fill('asdnklnas');
  await expect(page.getByLabel('Open').first()).toBeVisible();
  await page.getByLabel('Elegir Actividad').click();
  await page.getByRole('combobox', { name: 'Elegir Actividad' }).fill('dfsdf');
  await page.getByLabel('Elegir Actividad').click();
  await page.getByLabel('Elegir Actividad').fill('');
  await expect(page.locator('#activity-option-0')).toContainText('Futbol 5');
  await expect(page.locator('#activity-option-1')).toContainText('Futbol 8');
  await expect(page.locator('#activity-option-2')).toContainText('Futbol 7');
  await page.getByRole('option', { name: 'Futbol 5' }).click();
  await page.getByLabel('Open').nth(1).click();
  await page.getByRole('option', { name: 'Villa del Parque' }).click();
  await expect(page.locator('div:nth-child(3) > .MuiFormControl-root > .MuiInputBase-root')).toBeVisible();
  await page.getByPlaceholder('MM/DD/YYYY').click();
  await page.getByLabel('Choose date').click();
  await page.getByRole('gridcell', { name: '23' }).click();
  await page.getByRole('button', { name: 'Buscar' }).click();
  await expect(page.locator('div:nth-child(2) > .MuiGrid-root').first()).toBeVisible();
  await page.getByRole('button', { name: 'Ver Más' }).first().click();
  await expect(page.locator('#root')).toContainText('Evento:');
  await expect(page.locator('#root')).toContainText('Futbol 5');
  await expect(page.locator('#root')).toContainText('Quedan 9 lugares');
  await expect(page.locator('#root')).toContainText('Mensaje del organizador:Partido para mayores de 30!! llevar plata!');
  await page.getByRole('button', { name: '¡Me Sumo!' }).click();
  await expect(page.getByRole('dialog')).toContainText('¡Sumado!Ya estás participando ;D¡OK!');
  await page.getByRole('button', { name: '¡OK!' }).click();
  await expect(page.locator('#root')).toContainText('Me Bajo');
  await expect(page.locator('#root')).toContainText('Quedan 8 lugares');
  await page.getByRole('button', { name: 'Me Bajo' }).click();
  await expect(page.getByRole('dialog')).toContainText('Lamentamos no contar con vos¡OK!');
  await page.getByRole('button', { name: '¡OK!' }).click();
  await expect(page.locator('#root')).toContainText('Quedan 9 lugares');
  await page.getByText('F', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});

test('Sumarse a evento con usuario no logueado', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Buscar' }).click();
  await page.goto('http://localhost:5173/');
  await page.getByLabel('Open').first().click();
  await page.getByRole('option', { name: 'Futbol 7' }).click();
  await page.getByLabel('Open').nth(1).click();
  await page.getByRole('option', { name: 'Nuñez' }).click();
  await page.getByLabel('Choose date').click();
  await page.getByRole('gridcell', { name: '15' }).click();
  await page.getByRole('button', { name: 'Buscar' }).click();
  await expect(page.locator('div:nth-child(2) > .MuiGrid-root').first()).toBeVisible();
  await expect(page.getByRole('button', { name: 'Ver Más' }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Ver Más' }).first().click();
  await expect(page.getByRole('button', { name: '¡Me Sumo!' })).toBeVisible();
  await page.getByRole('button', { name: '¡Me Sumo!' }).click();
  await expect(page.getByText('¡Hola!Tenés que estar')).toBeVisible();
  await page.getByRole('button', { name: '¡OK!' }).click();
  await expect(page.getByRole('button', { name: '¡Me Sumo!' })).toBeVisible();
});