import { test, expect } from '@playwright/test';


test('Desde club - crear un evento con usuario logueado', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('jilmelarke@gufum.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('89898989');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.locator('div').filter({ hasText: '¡Hola Fran!' }).nth(4)).toBeVisible();
  await page.getByRole('tab', { name: 'Clubes' }).click();
  await page.getByRole('button', { name: 'Ver Más' }).first().click();
  await expect(page.getByRole('heading', { name: 'Futbol Retiro | Padre Carlos Mujica 199' })).toBeVisible();
  await expect(page.getByText('Futbol Retiro, un club')).toBeVisible();
  await expect(page.getByText('HorariosLunes, Martes,')).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Canchas y disponibilidad' })).toBeVisible();
  await page.locator('div:nth-child(3) > .MuiPaper-root > .MuiCardContent-root > .MuiPickersLayout-root > .MuiPickersLayout-contentWrapper > .MuiDateCalendar-root > div:nth-child(2) > div > .MuiDayCalendar-root > .MuiPickersSlideTransition-root > .MuiDayCalendar-monthContainer > div:nth-child(3) > button:nth-child(4)').click();
  await page.getByRole('button', { name: ':00' }).click();
  await page.locator('div:nth-child(3) > .MuiPaper-root > .MuiCardContent-root > div:nth-child(5) > .MuiTypography-root > .MuiButtonBase-root').click();
  await page.locator('form div').filter({ hasText: 'Nombre del evento' }).nth(1).click();
  await page.getByLabel('Nombre del evento').fill('Ganador se lleva 100k usd');
  await page.getByLabel('Nombre del evento').press('Tab');
  await page.getByLabel('Mensaje del organizador').fill('Unicamente apasionados por la redonda');
  await expect(page.getByRole('heading', { name: 'Informacion del Evento' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Crear evento' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear evento' }).click();
  await expect(page.getByRole('heading', { name: '¡Evento creado con éxito!' })).toBeVisible();
  await page.getByText('F', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});

test('Desde club - crear un evento con usuario no logueado', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await page.getByRole('tab', { name: 'Clubes' }).click();
  await expect(page.locator('div').filter({ hasText: /^12345…8$/ })).toBeVisible();
  await page.getByText('ClubesClub: Futbol').click();
  await expect(page.getByText('ClubesClub: Futbol')).toBeVisible();
  await page.getByRole('button', { name: 'Ver Más' }).nth(1).click();
  await expect(page.locator('div:nth-child(4) > div').first()).toBeVisible();
  await page.locator('div:nth-child(5) > button:nth-child(5)').first().click();
  await page.locator('.MuiTypography-root > .MuiButtonBase-root').first().click();
  await expect(page.getByRole('heading', { name: 'Informacion del Evento' })).toBeVisible();
  await page.getByLabel('Nombre del evento').click();
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('E');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('El mejor evento');
  await page.getByLabel('Nombre del evento').press('Tab');
  await page.getByLabel('Mensaje del organizador').press('CapsLock');
  await page.getByLabel('Mensaje del organizador').fill('Q');
  await page.getByLabel('Mensaje del organizador').press('CapsLock');
  await page.getByLabel('Mensaje del organizador').fill('Quiero jugar al fuchibol');
  await page.getByRole('button', { name: 'Crear evento' }).click();
  await expect(page.getByText('¡Hola!Tenés que estar')).toBeVisible();
  await page.getByRole('button', { name: '¡OK!' }).click();
});

test('Creacion evento desde miPerfil', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('jilmelarke@gufum.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('89898989');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.getByText('¡Hola Fran!')).toBeVisible();
  await expect(page.locator('header').filter({ hasText: '¡Hola Fran!' }).locator('div').nth(3)).toBeVisible();
  await page.getByText('F', { exact: true }).click();
  await expect(page.getByRole('link', { name: 'Mi Perfil' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cerrar Sesión' })).toBeVisible();
  await page.getByRole('link', { name: 'Mi Perfil' }).click();
  await expect(page.getByRole('heading', { name: 'Tus datos' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tus eventos' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Crear evento' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Guardar Cambios' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear evento' }).click();
  await expect(page.getByRole('heading', { name: 'Canchas disponibles', exact: true })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Buscar disponibilidad' })).toBeVisible();
  await page.getByLabel('Open').first().click();
  await page.getByRole('option', { name: 'Futbol 8' }).click();
  await page.getByLabel('Open').nth(1).click();
  await page.getByRole('option', { name: 'Ciudad (Ex-Muni)' }).click();
  await page.getByRole('button', { name: 'Buscar' }).click();
  await expect(page.getByRole('button', { name: 'Cancha 4 F8 | Ciudad (Ex-Muni' })).toBeVisible();
  await page.getByRole('button', { name: 'Cancha 4 F8 | Ciudad (Ex-Muni' }).click();
  await page.getByRole('gridcell', { name: '29' }).click();
  await page.getByRole('button', { name: ':00' }).click();
  await page.getByRole('button', { name: 'Confirmar evento' }).click();
  await page.getByLabel('Nombre del evento').click();
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('S');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('A');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del ');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del F');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del ');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del J');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del Joga ');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del Joga B');
  await page.getByLabel('Nombre del evento').press('CapsLock');
  await page.getByLabel('Nombre del evento').fill('Amantes del Joga Bonito');
  await page.getByLabel('Nombre del evento').press('Tab');
  await page.getByLabel('Mensaje del organizador').press('CapsLock');
  await page.getByLabel('Mensaje del organizador').fill('P');
  await page.getByLabel('Mensaje del organizador').press('CapsLock');
  await page.getByLabel('Mensaje del organizador').fill('Personas +30, sin hijos y con pulmones, porfavor!');
  await expect(page.getByRole('button', { name: 'Crear evento' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear evento' }).click();
  await expect(page.getByRole('heading', { name: '¡Evento creado con éxito!' })).toBeVisible();
  await page.getByText('F', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Registrarse' })).toBeVisible();
});