import { test, expect } from '@playwright/test';

test('Creacion de nueva cancha con rol club', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('kickfc@gmail.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('distrito1234');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.getByText('¡Hola Kick FC!')).toBeVisible();
  await page.getByText('K', { exact: true }).click();
  await expect(page.getByRole('link', { name: 'Reservas' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cargar Cancha' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cerrar Sesión' })).toBeVisible();
  await page.getByRole('link', { name: 'Reservas' }).click();
  await expect(page.getByRole('heading', { name: 'Reservas del Club' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Horarios de turnos' })).toBeVisible();
  await page.getByRole('button', { name: 'Horarios de turnos' }).click();
  await expect(page.getByRole('heading', { name: 'Turnos en tus canchas' })).toBeVisible();
  await expect(page.getByText('Agregar Franja Horaria')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Agregar' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Volver a reservas' })).toBeVisible();
  await page.getByRole('button', { name: 'Volver a reservas' }).click();
  await page.getByText('K', { exact: true }).click();
  await page.getByRole('link', { name: 'Cargar Cancha' }).click();
  await expect(page.getByRole('heading', { name: 'Crear nueva cancha' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Datos de la cancha a crear' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tus canchas' })).toBeVisible();
  await page.getByRole('button', { name: 'Futbol 5' }).click();
  await page.getByRole('button', { name: 'Futbol 8' }).click();
  await page.getByLabel('Crear Nombre').click();
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('C');
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('Cancha 9');
  await page.getByLabel('Open').first().click();
  await page.getByRole('option', { name: 'Fútbol 8' }).click();
  await page.getByLabel('Elegir Suelo').click();
  await page.getByRole('option', { name: 'CEMENTO' }).click();
  await page.getByLabel('Open').nth(2).click();
  await page.getByRole('option', { name: 'SÍ' }).click();
  await expect(page.getByRole('button', { name: 'Crear cancha' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear cancha' }).click();
  await expect(page.getByText('Cancha Creada¡La cancha se ha')).toBeVisible();
  await page.getByRole('button', { name: '¡OK!' }).click();
  await page.getByText('K', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});

test('Verificacion de canchas cargadas con rol club', async ({ page }) => {
  await page.goto('http://localhost:5173/');
  await expect(page.getByRole('button', { name: 'Iniciar sesión' })).toBeVisible();
  await page.getByRole('button', { name: 'Iniciar sesión' }).click();
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('kickfc@gmail.com');
  await page.getByPlaceholder('Email').press('Tab');
  await page.getByPlaceholder('Contraseña').fill('distrito1234');
  await page.getByRole('button', { name: 'Iniciar Sesión', exact: true }).click();
  await expect(page.getByText('¡Hola Kick FC!')).toBeVisible();
  await page.getByText('K', { exact: true }).click();
  await expect(page.getByRole('link', { name: 'Reservas' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cargar Cancha' })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Cerrar Sesión' })).toBeVisible();
  await page.getByRole('link', { name: 'Cargar Cancha' }).click();
  await expect(page.getByRole('heading', { name: 'Crear nueva cancha' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Tus canchas' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Datos de la cancha a crear' })).toBeVisible();
  await page.getByLabel('Crear Nombre').click();
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('C');
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('Cancha 8 ');
  await page.getByLabel('Crear Nombre').press('CapsLock');
  await page.getByLabel('Crear Nombre').fill('Cancha 8 F8');
  await page.getByLabel('Open').first().click();
  await page.getByRole('option', { name: 'Fútbol 8' }).click();
  await page.getByLabel('Open').nth(1).click();
  await page.getByRole('option', { name: 'CESPED_NATURAL' }).click();
  await page.getByLabel('Open').nth(2).click();
  await page.getByRole('option', { name: 'NO' }).click();
  await expect(page.getByRole('button', { name: 'Crear cancha' })).toBeVisible();
  await page.getByRole('button', { name: 'Crear cancha' }).click();
  await expect(page.getByRole('heading', { name: 'Cancha Creada' })).toBeVisible();
  await expect(page.getByText('Cancha Creada¡La cancha se ha')).toBeVisible();
  await page.getByRole('button', { name: '¡OK!' }).click();
  await page.getByText('K', { exact: true }).click();
  await page.getByRole('link', { name: 'Cerrar Sesión' }).click();
});